### ISSUE TITLE
Enable dependabot on micrometer branch

### ISSUE THREAD

**Issue by donbourne** [smallrye/smallrye-metrics#586]

**Comment by Channyboy** [comment]
https://github.com/smallrye/smallrye-metrics/blob/main/.github/dependabot.yml has been updated to be:
```
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "micrometer"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels: 
      - "micrometer"
      - "dependencies"
 ```
